dist: trusty
language: php

php:
    - 5.6
    - 7.1

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=1

before_script:
    - composer self-update
    - make deps
    - chmod +x src/tests/init.sh && bash src/tests/init.sh $TRAVIS_PHP_VERSION $WP_VERSION

script: cd src && phpunit
